const L                   = require('lazy.js')

const { connection }      = require('./source/utils/db')

const { v4: uuid }        = require('uuid')

const { trace
      , rndmString
      }                   = require('./source/utils/helpers')

const { removeAll 
      , insertGen
      }                   = require('./source/API/controller.db')

const { chunk
      , head 
      }                   = require('lodash/fp')

const { N
      , HOST
      , DATABASE
      , GENNUMBER
      , TELLENGTH
      , PSSWDLENGTH
      , HASHTAGLENGTH
      }                   = require('dotenv').config().parsed

const lazyTelephones      = L.generate(x => [Number('1'.concat(x.toString().padStart(TELLENGTH - 1, 0))),
                                             rndmString(HASHTAGLENGTH),
                                             rndmString(PSSWDLENGTH)
                                            ])

const generateContacts    = (gens, nContacts) => gens.map(
                                                  gen => trace(gen.map(
                                                    row => [head(row),
                                                            L.generate(x => x.toString().padStart(TELLENGTH - 1, 0))
                                                             .take(100)
                                                             .toArray()
                                                             .map(y => Number(head(row)
                                                                                .toString()
                                                                                .replace(/[1-9]+[0]*/, '')
                                                                                .concat(y)))
                                                           ]))
                                                          )

                          connection.connect((e) => e ? trace(e.message) : trace(`\n\nMySQL DB "${DATABASE}" connect on ${HOST}.\n`))
                          
                          removeAll(connection, 'users')

                          console.time(`\n${N/1000000}M records generated by Lazy.js in`)

                          const gens = chunk(N/GENNUMBER, lazyTelephones.take(N).toArray())
                          
                          console.timeEnd(`\n${N/1000000}M records generated by Lazy.js in`)

                          console.time(`\nContacts for ${N/1000000}M users generated in`)
                          
                          const contacts = chunk(N, generateContacts(gens))

                          console.timeEnd(`\nContacts for ${N/1000000}M users generated in`)
                          
                          // trace('\nSending generation to MySQL.\n')
                          
                          // gens.map((gen, i) => insertGen([connection, gen, uuid(), i, gen.length]))
                          
                          trace('\nNode.js finished the work.')
                          
                          connection.end((e) => e ? trace(e.message) : trace(`\nMySQL DB "${DATABASE}" disconnected.\n`))
