const { N
      , HOST
      , TMPPATH
      , TMPFILE
      , DATABASE
      , GENNUMBER
      , TELLENGTH
      , PSSWDLENGTH
      , HASHTAGLENGTH
      , MINCONTACTSNUMBER
      , MAXCONTACTSNUMBER
      }                   = require('dotenv').config().parsed

const { trace }           = require('./source/utils/helpers')

const { removeAll }       = require('./source/DB.API/db.controllers')

const { connection }      = require('./source/utils/db')

const { phonesIO
      , contactsIO
      }                   = require('./index')

                          // connection.connect((e) => e ? trace(e.message) : trace(`\nMySQL DB "${DATABASE}" connect on ${HOST}.\n`))
                          
                          // removeAll(connection, 'users')
                          
                          // removeAll(connection, 'contacts')

                          // console.time(`\n${N/1000000}M phones generated by Lazy.js in`)

                          // phonesIO(N, GENNUMBER, TELLENGTH, PSSWDLENGTH, HASHTAGLENGTH).run()
                          
                          // console.timeEnd(`\n${N/1000000}M phones generated by Lazy.js in`)

                          // console.time(`\nContacts for ${N/1000000}M users generated in`)
                          
                          // contactsIO(TMPPATH, TMPFILE)
                          
                          // console.timeEnd(`\nContacts for ${N/1000000}M users generated in`)
                          
                          // connection.end((e) => e ? trace(e.message) : trace(`\nMySQL DB "${DATABASE}" disconnected.\n`))
